
#ansible-playbook playbook_configuration_ec2.yml -i hosts 

---
- name: Let's copy our executable script to remote location, execute script and get result back.
  hosts: all
  remote_user: vagrant
  tasks:
     - name: Transfer executable script script
       copy: src=./configuration.sh dest=/home/vagrant/ mode=0777

     - name: Execute the script
       command: sudo -S su root -c "~/configuration.sh"
